country_list = ['france','japan','russia','germany','iraq']
print(country_list)
print(sorted(country_list))
print(country_list)
print(sorted(country_list))
print(country_list)
country_list.reverse()
print(country_list)
country_list.reverse()
print(country_list)
country_list.sort()
print(country_list)
country_list.sort(reverse=True)
print(country_list)
